name: Build and test TicTacToe on push

run-name: Build run ${{ github.run_id }} by ${{ github.actor }}

on: push

jobs:
  
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      #- name: Install required dependencies
      #  run: sudo apt-get update && sudo apt-get install -y libidn11

      # Add steps to download and install libidn11 package
      - name: Download libidn11 package
        run: wget http://mirrors.kernel.org/ubuntu/pool/main/libi/libidn/libidn11_1.33-2.2ubuntu2_amd64.deb -O libidn11.deb 

      - name: Install libidn11 package
        run: sudo dpkg -i libidn11.deb
        if: success()  # Only install if the download is successful

      - name: Set up CMake
        uses: jwlawson/actions-setup-cmake@v2
        with:
          cmake-version: '3.5'  # Adjust the CMake version as needed

      - name: Verify CMake installation
        run: cmake --version

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: '6.6.0'  # Adjust the Qt version as needed

      - name: Print Environment Variables
        run: |
          env

      #- name: Verify Qt installation
      #  run: qtchooser -print-env

      #- name: Configure TicTacToe project
      #  run: cmake -B build -S ./TicTacToe

      #- name: Build project
      #  run: cmake --build build --config Release

      # - name: Run tests
      #   run: cd build && ctest -C Release --output-on-failure

      # - name: Run test executable
      #   run: ./build/tests
      