name: Build and test TicTacToe on push

run-name: Build run ${{ github.run_id }} by ${{ github.actor }}

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install required dependencies
        run: sudo apt-get update && sudo apt-get install -y libidn11
        
      - name: Set up CMake
        uses: jwlawson/actions-setup-cmake@v2
        with:
          cmake-version: '3.5'  # Adjust the CMake version as needed

      - name: Verify CMake installation
        run: cmake --version

      - name: Set up Qt
        uses: jurplel/install-qt-action@v3
        with:
          qt-version: '6.6.0'  # Adjust the Qt version as needed

      - name: Verify Qt installation
        run: qtchooser -print-env

      - name: Configure TicTacToe project
        run: cmake -B build -S ./QtIntroProjects/TicTacToe

      - name: Build project
        run: cmake --build build --config Release

      # - name: Run tests
      #   run: cd build && ctest -C Release --output-on-failure